capp/carbon_app/forms.py
from flask_wtf import FlaskForm
from wtforms import  SubmitField,  SelectField,  FloatField
from wtforms.validators import InputRequired

class BusForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Biodiesel', 'Biodiesel')])
  submit = SubmitField('Submit')

class CarForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('Old Petrol', 'Old Petrol Car'), ('Old Diesel', 'Old Diesel Car'),('New Diesel', 'New Diesel Car'), ('New Petrol', 'New Petrol Car'), ('Small Electric', 'Small Electric Car'), ('Medium Electric', 'Medium Electric Car'), ('Large Electric', 'Large Electric Car')])
  submit = SubmitField('Submit')  

class PlaneForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
   choices=[('Long-haul Economy class', 'Long-haul Economy Class Plane'), ('Long-haul Business class', 'Long-haul Business Class Plane'), ('Long-haul First class', 'Long-haul First Class Plane'), ('Short-haul Economy class', 'Short-haul Economy Class Plane'), ('Short-haul Business class', 'Short-haul Business Class Plane'), ('Short-haul First class', 'Short-haul First Class Plane')])
  submit = SubmitField('Submit')
  
class FerryForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('Diesel', 'Diesel'), ('Electric', 'Electric'),])
  submit = SubmitField('Submit')  

class MotorbikeForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('Petrol', 'Petrol')])
  submit = SubmitField('Submit')

class TrainForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
   choices=[('Diesel', 'Diesel'), ('Electric Nordic', 'Electric Nordic Train'), ('Electric European', 'Electric European Train')])

  submit = SubmitField('Submit')

class BicycleForm(FlaskForm):
    kms = FloatField('Kilometers', [InputRequired()])
    fuel_type = SelectField('Type of Fuel', [InputRequired()], 
                            choices=[('No fossil fuel', 'No fossil fuel')])
    submit = SubmitField('Submit')  

class WalkForm(FlaskForm):
    kms = FloatField('Kilometers', [InputRequired()])
    fuel_type = SelectField('Type of Fuel', [InputRequired()], 
                            choices=[('No fossil fuel', 'No fossil fuel')])
    submit = SubmitField('Submit')

capp/carbon_app/__init__.py
#

capp/carbon_app/routes.py
from flask import render_template, Blueprint, request, redirect, url_for, flash
from capp.models import Transport
from capp import db
from datetime import timedelta, datetime
from flask_login import login_required, current_user
from capp.carbon_app.forms import BusForm, CarForm, PlaneForm, FerryForm, MotorbikeForm, BicycleForm, WalkForm, TrainForm 
import json

carbon_app = Blueprint('carbon_app', __name__)

# Emissions factor per transport in kg per passenger km
efco2 = {
    'Bus': {'Diesel': 0.025, 'Electric': 0.013, 'Biodiesel': 0.007},
    'Car': {'Old Petrol': 0.156, 'New Petrol': 0.139, 'Old Diesel': 0.130, 'New Diesel': 0.122, 'Small Electric': 0.012, 'Medium Electric': 0.016, 'Large Electric': 0.020},
    'Plane': {'Long-haul Economy class': 0.102, 'Long-haul Business class':0.306, 'Long-haul First class':0.408, 'Short-haul Economy class':0.133,'Short-haul Business class':0.399, 'Short-haul First class':0.532},
    'Ferry': {'Diesel': 0.226, 'Electric': 0.00525},
    'Motorbike': {'Petrol': 0.114},
    'Train':{'Diesel':0.091, 'Electric Nordic':0.007 , 'Electric European': 0.024},
    'Bicycle': {'No Fossil Fuel': 0},
    'Walk': {'No Fossil Fuel': 0}
}


@carbon_app.route('/')
@carbon_app.route('/carbon_app')
def carbon_app_home():
    return render_template('carbon_app/carbon_app.html', title='carbon_app')


@carbon_app.route('/carbon_app/new_entry')
@login_required
def new_entry():
    return render_template('carbon_app/new_entry.html', title='new_entry')


@carbon_app.route('/carbon_app/your_data')
@login_required
def your_data():
    # Table
    entries = Transport.query.filter_by(author=current_user). \
        filter(Transport.date > (datetime.now() - timedelta(days=5))). \
        order_by(Transport.date.desc()).order_by(Transport.transport.asc()).all()

    # Emissions by category
    emissions_by_transport = db.session.query(db.func.sum(Transport.total), Transport.transport). \
        filter(Transport.date > (datetime.now() - timedelta(days=5))).filter_by(author=current_user). \
        group_by(Transport.transport).order_by(Transport.transport.asc()).all()
    emission_transport = [0, 0, 0, 0, 0, 0, 0, 0]
    first_tuple_elements = []
    second_tuple_elements = []
    for a_tuple in emissions_by_transport:
        first_tuple_elements.append(a_tuple[0])
        second_tuple_elements.append(a_tuple[1])

    if 'Bus' in second_tuple_elements:
        index_bus = second_tuple_elements.index('Bus')
        emission_transport[0] = first_tuple_elements[index_bus]

    if 'Car' in second_tuple_elements:
        index_car = second_tuple_elements.index('Car')
        emission_transport[1] = first_tuple_elements[index_car]

    if 'Ferry' in second_tuple_elements:
        index_ferry = second_tuple_elements.index('Ferry')
        emission_transport[2] = first_tuple_elements[index_ferry]

    if 'Motorbike' in second_tuple_elements:
        index_motorbike = second_tuple_elements.index('Motorbike')
        emission_transport[3] = first_tuple_elements[index_motorbike]

    if 'Plane' in second_tuple_elements:
        index_plane = second_tuple_elements.index('Plane')
        emission_transport[4] = first_tuple_elements[index_plane]

    if 'Train' in second_tuple_elements:
        index_train = second_tuple_elements.index('Train')
        emission_transport[5] = first_tuple_elements[index_train]

    if 'Bicycle' in second_tuple_elements:
        index_bicycle = second_tuple_elements.index('Bicycle')
        emission_transport[6] = first_tuple_elements[index_bicycle]

    if 'Walk' in second_tuple_elements:
        index_walk = second_tuple_elements.index('Walk')
        emission_transport[7] = first_tuple_elements[index_walk]

    # Kilometers by category
    kms_by_transport = db.session.query(db.func.sum(Transport.kms), Transport.transport). \
        filter(Transport.date > (datetime.now() - timedelta(days=5))).filter_by(author=current_user). \
        group_by(Transport.transport).order_by(Transport.transport.asc()).all()
    kms_transport = [0, 0, 0, 0, 0, 0, 0, 0]
    first_tuple_elements = []
    second_tuple_elements = []
    for a_tuple in kms_by_transport:
        first_tuple_elements.append(a_tuple[0])
        second_tuple_elements.append(a_tuple[1])

    if 'Bus' in second_tuple_elements:
        index_bus = second_tuple_elements.index('Bus')
        kms_transport[0] = first_tuple_elements[index_bus]

    if 'Car' in second_tuple_elements:
        index_car = second_tuple_elements.index('Car')
        kms_transport[1] = first_tuple_elements[index_car]

    if 'Ferry' in second_tuple_elements:
        index_ferry = second_tuple_elements.index('Ferry')
        kms_transport[2] = first_tuple_elements[index_ferry]

    if 'Motorbike' in second_tuple_elements:
        index_motorbike = second_tuple_elements.index('Motorbike')
        kms_transport[3] = first_tuple_elements[index_motorbike]

    if 'Plane' in second_tuple_elements:
        index_plane = second_tuple_elements.index('Plane')
        kms_transport[4] = first_tuple_elements[index_plane]

    if 'Train' in second_tuple_elements:
        index_train = second_tuple_elements.index('Train')
        kms_transport[5] = first_tuple_elements[index_train]

    if 'Bicycle' in second_tuple_elements:
        index_bicycle = second_tuple_elements.index('Bicycle')
        kms_transport[6] = first_tuple_elements[index_bicycle]

    if 'Walk' in second_tuple_elements:
        index_walk = second_tuple_elements.index('Walk')
        kms_transport[7] = first_tuple_elements[index_walk]

    # Emissions by date (individual)
    emissions_by_date = db.session.query(db.func.sum(Transport.total), Transport.date). \
        filter(Transport.date > (datetime.now() - timedelta(days=5))).filter_by(author=current_user). \
        group_by(Transport.date).order_by(Transport.date.asc()).all()
    over_time_emissions = []
    dates_label = []
    for total, date in emissions_by_date:
        dates_label.append(date.strftime("%m-%d-%y"))
        over_time_emissions.append(total)

    # Kms by date (individual)
    kms_by_date = db.session.query(db.func.sum(Transport.kms), Transport.date). \
        filter(Transport.date > (datetime.now() - timedelta(days=5))).filter_by(author=current_user). \
        group_by(Transport.date).order_by(Transport.date.asc()).all()
    over_time_kms = []
    dates_label = []
    for total, date in kms_by_date:
        dates_label.append(date.strftime("%m-%d-%y"))
        over_time_kms.append(total)

    return render_template('carbon_app/your_data.html', title='your_data', entries=entries,
                           emissions_by_transport_python_dic=emissions_by_transport,
                           emission_transport_python_list=emission_transport,
                           emissions_by_transport=json.dumps(emission_transport),
                           kms_by_transport=json.dumps(kms_transport),
                           over_time_emissions=json.dumps(over_time_emissions),
                           over_time_kms=json.dumps(over_time_kms),
                           dates_label=json.dumps(dates_label))

#Delete emission
@carbon_app.route('/carbon_app/delete-emission/<int:entry_id>')
def delete_emission(entry_id):
    entry = Transport.query.get_or_404(int(entry_id))
    db.session.delete(entry)
    db.session.commit()
    flash("Entry deleted", "success")
    return redirect(url_for('carbon_app.your_data')) 

@carbon_app.route('/carbon_app/new_entry_bus', methods=['GET', 'POST'])
@login_required
def new_entry_bus():
    form = BusForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Bus'

        co2 = float(kms) * efco2[transport][fuel]
        total = co2

        co2 = float("{:.2f}".format(co2))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('/carbon_app/new_entry_bus.html', title='new_entry_bus', form=form)


@carbon_app.route('/carbon_app/new_entry_car', methods=['GET', 'POST'])
@login_required
def new_entry_car():
    form = CarForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Car'

        co2 = float(kms) * efco2[transport][fuel]
        total = co2

        co2 = float("{:.2f}".format(co2))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('/carbon_app/new_entry_car.html', title='new_entry_car', form=form)


@carbon_app.route('/carbon_app/new_entry_ferry', methods=['GET', 'POST'])
@login_required
def new_entry_ferry():
    form = FerryForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Ferry'

        co2 = float(kms) * efco2[transport][fuel]
        total = co2

        co2 = float("{:.2f}".format(co2))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('/carbon_app/new_entry_ferry.html', title='new_entry_ferry', form=form)


@carbon_app.route('/carbon_app/new_entry_motorbike', methods=['GET', 'POST'])

capp/templates/carbon_app/carbon_app.html
{% extends "layout.html" %}
{% block content %}

    <!-- Header -->
    <section class="section_header_carbon_app">
        <div class="container">
    
            <div class="header_carbon_app">
                <div class="box"> 
                    <h1 style="font-size:55px;"><span class="text-logo"> CarbonCare Calculator</span></h1>
                    <p style="text-align:left;">
                       Welcome to our Carbon App Calculator. To commence, click the ‘New Entry’ button and input your travel history. Our application will furnish both a visual and quantitative breakdown of your travel-related emissions. In the event that an entry needs removal, users can scroll down to the table located at the bottom of the page and click the ‘Delete’ button next to the entry they wish to remove. Furthermore, the table provides additional filtering options, such as sorting by total kilometers traveled or transport mode. Additionally, a search bar facilitates the option to retrieve specific entries.            
                    </p>
                    <div class="container_buttons_links_header_carbon_app">
                        <div class="btn">
                            <a href="{{url_for('carbon_app.your_data')}}" class="btn btn-primary btn-lg mr-2" style="background-color:#35628f;">Your data</a>
                        </div>
                    </div>  
                </div>
                <div class="box">
                    <img 
                        src="{{url_for('static', filename='icons/calculator.svg')}}"
                        width="325" 
                        height="325"
                        alt=""/>
                </div>
            </div>
        
        </div>
    </section> 

    <!-- carbon_app_new_entry_main -->
    <section class="section_carbon_app_new_entry_main">
        <div class="container">
        
            <div class="carbon_app_new_entry_main" style="display:block;">
                <br>
                <h3 style="text-align:center;">Select your transport method</h3>     
            </div>
        
            <div class="carbon_app_new_entry_main">
                <div class="box">
                    <div class="h1 mb-3" style="text-align: center;">
                        <i class="fa-solid fa-bus"></i>
                    </div>
                    <h3>Bus</h3>
                    <div class="section_container_buttons_carbon_app_new_entry_main">
                        <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_bus')}}" style="background-color:#2a4359;">New Entry</a>
                    </div> 
                </div>
                <div class="box">
                    <div class="h1 mb-3" style="text-align: center;">
                        <i class="fa-solid fa-car"></i>
                    </div>
                    <h3>Car</h3>
                    <div class="section_container_buttons_carbon_app_new_entry_main">
                        <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_car')}}" style="background-color:#2a4359;">New Entry</a>
                    </div> 
                </div>           
                <div class="box">
                    <div class="h1 mb-3" style="text-align: center;">
                        <i class="fa-solid fa-plane"></i>
                    </div>
                    <h3>Plane</h3>
                    <div class="section_container_buttons_carbon_app_new_entry_main">
                        <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_plane')}}" style="background-color:#2a4359;">New Entry</a>
                    </div> 
                </div>
                <div class="box">
                    <div class="h1 mb-3" style="text-align: center;">
                        <i class="fa-solid fa-ship"></i>
                    </div>
                    <h3>Ferry</h3>
                    <div class="section_container_buttons_carbon_app_new_entry_main">
                        <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_ferry')}}" style="background-color:#2a4359;">New Entry</a>
                    </div> 
                </div>      
            </div>

            <div class="carbon_app_new_entry_main">
                <div class="box">
                    <div class="h1 mb-3" style="text-align: center;">
                        <i class="fa-solid fa-motorcycle"></i>
                    </div>
                    <h3>Motorbike</h3>
                    <div class="section_container_buttons_carbon_app_new_entry_main">
                        <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_motorbike')}}" style="background-color:#2a4359;">New Entry</a>
                    </div> 
                </div>   
                <div class="box">   
                  <div class="h1 mb-3" style="text-align: center;">
                    <i class="fa-solid fa-train"></i>
                  </div> 
                <h3>Train</h3>
                <div class="section_container_buttons_carbon_app_new_entry_main">
                  <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_train')}}", style=background-color:#2a4359; >New Entry</a>
                </div>
                  </div>
                <div class="box">
                    <div class="h1 mb-3" style="text-align: center;">
                        <i class="fa-solid fa-bicycle"></i>
                    </div>
                    <h3>Bicycle</h3>
                    <div class="section_container_buttons_carbon_app_new_entry_main">
                        <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_bicycle')}}" style="background-color:#2a4359;">New Entry</a>
                    </div> 
                      </div>
                    <div class="box">
                     <div class="h1 mb-3" style="text-align: center;">
                        <i class="fa-solid fa-person-walking"></i>
                      </div>
                    <h3>Walk</h3>
                    <div class="section_container_buttons_carbon_app_new_entry_main">
                        <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_walk')}}" style="background-color:#2a4359;">New Entry</a>
                    </div> 
                </div>     
            </div>
        
        </div>          
    </section>
      
    <div class="container">
        <div class="footer">
            <h1> 
                <a href="#">
                    <i class="fa-solid fa-circle-up" style="color:#2a4359"> Back to top</i>
                </a>
            </h1>
        </div>
    </div>
  
{% endblock content %}¨



capp/templates/carbon_app/new_entry_bicycle.html
{% extends "layout.html" %}
{% block content %}

<section class="new_entry">
  <div class="container">
      <div class="box">

      </div>
      <div class="box">   
        <div class="h1 mb-3" style="text-align: center;">
          <i class="fa-solid fa-bicycle"></i>
        </div>
        <h3>Bicycle</h3>
        <p>
          <ol style="text-align: left;">
            <li>
              Please, enter the number of kilometers.
            </li>
          </ol>
        </p>
          <form method="POST" action="">
              {{ form.csrf_token }}
              <fieldset class="form-group">

                <div class="form-group">
                    {{ form.kms.label(class="form-control-label") }}
                    {% if form.kms.errors %}
                        {{ form.kms(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.kms.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.kms(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.fuel_type.label(class="form-control-label") }}
                    {% if form.fuel_type.errors %}
                        {{ form.fuel_type(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.fuel_type.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.fuel_type(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

              </fieldset>
              </br>
              <div class="form-group">
                {{ form.submit(class="btn_carbon_app_new_entry_main") }}
              </div>
          </form>
      </div>
      <div class="box">

      </div>
  </div>
</section> 

        
{% endblock content %}

capp/templates/carbon_app/your_data.html

{% extends "layout.html" %}
{% block content %}

    <!-- New Entry Section -->
    <section class="main_menu">
      <div class="container">
          <div class="box">

          </div>
          <div class="box" style=background-color:#2a4359;> 
              <div class="container_buttons_links_main_menu">
                  <div class="btn">
                      <a href="{{ url_for('carbon_app.carbon_app_home') }}" class="btn_carbon_app_new_entry_main",  style=background-color:#35628f;>New entry</a>
                  </div>   
              </div>        
          </div>
          <div class="box">

          </div>
      </div>
    </section> 
 
 
    <!-- Two Emissions Graph Section -->
    <section class="two_emissions_graphs">
        <div class="container">
            <div class="box", style=background-color:#35628f;>
                <canvas id="emissions_by_transport"></canvas>
            </div>
            <div class="box", style=background-color:#35628f;>
                <canvas id="over_time_emissions"></canvas> 
            </div>
        </div>
    </section> 

    <!-- Two Emissions Graph Section -->
    <section class="two_emissions_graphs">
        <div class="container">
            <div class="box", style=background-color:#35628f;>
                <canvas id="kms_by_transport"></canvas>
            </div>
            <div class="box", style=background-color:#35628f;>
                <canvas id="over_time_kms"></canvas>
            </div>
        </div>
    </section> 

    <!-- Table Section -->
    <section class="table_main">
    <div class="container">
        <div class="box", style=background-color:#35628f>
            
        </div>
        <div class="box", style=background-color:#35628f;>   
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}

                    {% endfor %}
                {% endif %}
            {% endwith %}         
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">User</th>
                        <th scope="col">Date</th>
                        <th scope="col">Kilometres</th>
                        <th scope="col">Transport</th>
                        <th scope="col">Fuel</th>
                        <th scope="col">Co2</th>
                        <th scope="col">Total</th>
                        <th scope="col">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for entry in entries %}
                        <tr>
                            <th scope="row">{{ current_user.username }}</th>
                            <td>{{ entry.date.strftime("%m-%d-%Y") }}</td>
                            <td>{{ entry.kms }}</td>
                            <td>{{ entry.transport }}</td>
                            <td>{{ entry.fuel }}</td>
                            <td>{{ entry.co2 }}</td>
                            <td>{{ entry.total }}</td>
                            <td><a href="{{ url_for('carbon_app.delete_emission', entry_id = entry.id) }}" class="btn btn-outline-danger btn-sm">Delete</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>       
        </div>
        <div class="box">

        </div>
    </div>
    </section> 


    {% block javascript %}
    <script>
        // Emissions
        let emission_transport_data = JSON.parse({{ emissions_by_transport | tojson }})    
        Chart.scaleService.updateScaleDefaults('linear', {
                ticks: {
                    min: 0
                }
        });
    
    
        let emissions_by_transport_chart = new Chart(emissions_by_transport, {
                type: 'pie',
                data: {
                labels: ['Bus', 'Car', 'Ferry', 'Motorbike', 'Plane', 'Train', 'Bicycle', 'Walk'],
                    datasets: [{
                        data: emission_transport_data,
                        backgroundColor: ['#9ac2be', '#f2e3b6', '#f2c299',
                            '#f2935c', '#5fd9cd', '#f2d95c', '#f2b84b', '#f27979' ],
    
                        borderWidth: 1,
                        hoverBorderColor: "white",
                        hoverBorderWidth: 2,
                        pointHoverRadius: 5
                    }],
                },
                options: {
                        title: {
                            display: true,
                                text: "Emissions by type of transport (5 last days)",
                                    fontColor: "white",
                                    fontSize: 20,
                        },
                        legend: {
                            position: "right",
                                labels: {
                                fontColor: "white"
                            },
                            display: true,
                        },
    
                        elements: {
                            hitRadius: 3,
                        }
                }
            })

        over_time_emissions = JSON.parse({{over_time_emissions | tojson}})
        labels = JSON.parse({{ dates_label  | tojson}})

        new Chart(document.getElementById("over_time_emissions"), {
                type: "line",
                data:
                {
                    labels: labels,
                    datasets: [
                        {
                        label: "Individual Emissions (5 past days)",                           
                        data: over_time_emissions,
                        fill: false,
                        borderColor: 'white',
                        lineTension: 0.1
                        }
                ]
                },                    
                options: {
                    legend: {
                                labels: {
                                fontColor: "white"
                            },
                            display: true,
                        }
                }
            });  
            
        // Kilometers
        let kms_transport_data = JSON.parse({{ kms_by_transport | tojson }})    
        Chart.scaleService.updateScaleDefaults('linear', {
                ticks: {
                    min: 0
                }
        });
        let kms_by_transport_chart = new Chart(kms_by_transport, {
                type: 'pie',
                data: {
                labels: ['Bus', 'Car', 'Ferry', 'Motorbike', 'Plane', 'Train', 'Bicycle', 'Walk'],
                    datasets: [{
                        label: "Income Vs Expenses",
                        data: kms_transport_data,
                        backgroundColor: ['#9ac2be', '#f2e3b6', '#f2c299',
                            '#f2935c', '#5fd9cd', '#f2d95c', '#f2b84b', '#f27979' ],    
                        borderWidth: 1,
                        hoverBorderColor: "white",
                        hoverBorderWidth: 2,
                        pointHoverRadius: 5
                    }],
                },
                options: {
                        title: {
                            display: true,
                                text: "Kilometers by type of transport (5 last days)",
                                fontColor: "white",
                                fontSize: 20,
                        },
                        legend: {
                            position: "right",
                                labels: {
                                fontColor: "white"
                            },
                            display: true,
                        },
    
                        elements: {
                            hitRadius: 3,
                        }
                }
            })
            
        over_time_kms = JSON.parse({{over_time_kms | tojson}})
        labels = JSON.parse({{ dates_label  | tojson}})

        new Chart(document.getElementById("over_time_kms"), {
                type: "line",
                data:
                {
                    labels: labels,
                    datasets: [
                        {
                        label: "Individual Kilometers (5 past days)",                            
                        data: over_time_kms,
                        fill: false,
                        borderColor: 'white',
                        lineTension: 0.1
                        }
                ]
                },                    
                options: {
                    legend: {
                                labels: {
                                fontColor: "white"
                            },
                            display: true,
                        }}
            });   

        </script>

   <div class="container">
        <div class="footer">
            <h1> 
                <a href="#">
                    <i class="fa-solid fa-circle-up" style="color:#35628f"> Back to top</i>
                </a>
            </h1>
        </div>

    {% endblock%}        
{% endblock content %}