capp/about_us/__init__.py
#

capp/about_us/routes.py
from flask import render_template, Blueprint

about_us=Blueprint('about_us',__name__)

@about_us.route('/about_us')
def about_us_home():
    return render_template('about_us.html', title='about_us')


capp/methodology/__init__.py
#

capp/methodology/routes.py
from flask import render_template, Blueprint

methodology=Blueprint('methodology',__name__)

@methodology.route('/methodology')
def methodology_home():
  return render_template('methodology.html', title='methodology')

capp/users/routes.py
from flask import render_template, Blueprint, redirect, flash, url_for
from capp import db, bcrypt
from capp.users.forms import RegistrationForm, LoginForm
from capp.models import User
from flask_login import login_user, current_user, logout_user
from wtforms.validators import ValidationError

users=Blueprint('users',__name__)

@users.route('/register', methods=['GET','POST'])
def register():
  form = RegistrationForm()
  if form.validate_on_submit():
      user_hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
      user = User(username=form.username.data, email=form.email.data, password=user_hashed_password)
      db.session.add(user)
      db.session.commit()
      login_user(user, remember=True)
      flash('Your account has been created! Now, you are able to login!', 'success')
      return redirect(url_for('carbon_app.carbon_app_home'))
  return render_template('users/register.html', title='register', form=form)

@users.route('/login', methods=['GET','POST'])
def login():
  form = LoginForm()
  if current_user.is_authenticated:
      return redirect(url_for('carbon_app.carbon_app_home'))
  
  if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
          if bcrypt.check_password_hash(user.password, form.password.data):
              login_user(user, remember=form.remember.data)
              flash('You have logged in! Now, you can start to use carbon app!', 'success')
              return redirect(url_for('carbon_app.carbon_app_home'))
          else:
            flash('Invalid email or password. Please try again', 'danger')
      
        else:
           flash('User does not exist. Please try again', 'danger')
     

  return render_template('users/login.html', title='login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('carbon_app.carbon_app_home'))

capp/templates/about_us.html
{% extends "layout.html" %}
{% block content %}

<!-- Header -->
<section class="section_header_about">
  <div class="container">

    <div class="header">
      <div class="box"> 
        <h1 style="font-size:55px;"><span class="text-logo"> About us</span></h1>
        <p style="text-align:left;">
         CarbonCare aims to address Europe’s significant carbon emissions from transportation by advocating for the adoption of lower-emission modes. Our initiative introduces a carbon emissions application, designed to raise individual awareness and facilitate the calculation of carbon footprints. Through analysis of various transportation modes, including cars, airplanes, ferries, trains, motorcycles, and buses, we emphasize the importance of informed choices in reducing environmental impact. CarbonCare is designed to encourage collective action to reduce carbon emissions.
        </p>
        <p>Our business model is founded on the increasing significance of opting for sustainable choices.</p>
          </div>
        </div>
        <div class="box">
          <img 
            src="{{url_for('static', filename='icons/about_us.svg')}}"
            width="325" 
            height="325"
            alt=""/>
        </div>
  </div>

</section>

  <!-- Developers -->
  <section class="section_developers">

      <div class="developers">
          <div class="box">
            <img src="https://github.com/edvardnt/carbon_app_2024_AWS/assets/160711399/c3fbca2d-0310-467e-9c3e-1bd2af305397" alt="" class="developer-photo">
            <h3>Edvard Nordstrand Tødenes</h3>
            <p> 
            </p>
            <div class="section_container_buttons_developers">
              <a class="btn_developers" href="https://www.facebook.com/profile.php?id=100002934759394"  target="_blank">Facebook</a>
            </div> 
          </div>
          <div class="box">
            <img src="https://github.com/edvardnt/carbon_app_2024_AWS/assets/160719390/8f5fae7a-3401-4eaf-8c3d-41926e78625f" alt="" class="developer-photo">
            <h3>Ola Børve</h3>
            <p>
            </p>
            <div class="section_container_buttons_developers">
              <a class="btn_developers" href="https://www.facebook.com/olaborve"  target="_blank">Facebook</a>
            </div> 
          </div>
      </div>
      
      <div class="developers">
          <div class="box2">
           <img src="https://github.com/edvardnt/carbon_app_2024_AWS/assets/160719390/21c45135-d296-49ca-b9a9-4a44f95a26d5" alt="" class="developer-photo">
            <h3>Benjamin Lien Larsen</h3>
            <p> 
            </p>
            <div class="section_container_buttons_developers">
              <a class="btn_developers" href="https://www.facebook.com/profile.php?id=100010429727707&sk=about"  target="_blank">Facebook</a>
            </div> 
          </div>           
          <div class="box2">
            <img src="https://github.com/edvardnt/carbon_app_2024_AWS/assets/160719390/c2ff9ce9-1c71-4472-8295-6fed3f3fa65e" alt="" class="developer-photo">
            <h3>Martin Trengereid</h3>
            <p> 
            </p>
            <div class="section_container_buttons_developers">
              <a class="btn_developers" href="https://www.facebook.com/martin.trengereid"  target="_blank">Facebook</a>
            </div> 
          </div>     
      </div>     

      <div class="developers">
        <div class="box3">
          <img src="https://github.com/edvardnt/carbon_app_2024_AWS/assets/160719390/44082e30-6fbb-4a30-9cfb-335b9e80bb44" alt="" class="developer-photo">
          <h3>Erik Berentsen</h3>
          <p> 
          </p>
          <div class="section_container_buttons_developers">
            <a class="btn_developers" href="https://www.facebook.com/profile.php?id=100010249211502"  target="_blank">Facebook</a>
          </div> 
        </div>
        <div class="box3">
          <img src="https://github.com/edvardnt/carbon_app_2024_AWS/assets/160719390/076c1f05-5053-49a7-901e-2ae029d015fc" alt="" class="developer-photo">
          <h3>Tomas Chernov</h3>
          <p> 
          </p>
          <div class="section_container_buttons_developers">
            <a class="btn_developers" href="https://www.facebook.com/tomas.chernov.9/friends"  target="_blank">Facebook</a>
          </div> 
        </div>           
        <div class="box3">
          <img src="https://github.com/edvardnt/carbon_app_2024_AWS/assets/160719390/86c07a8c-3609-42d9-a8a3-910304b2bba4" alt="" class="developer-photo">
          <h3>Tobias Ytterdahl Bergland</h3>
          <p> 
          </p>
          <div class="section_container_buttons_developers">
            <a class="btn_developers" href="https://www.facebook.com/tobias.bergland"  target="_blank">Facebook</a>
          </div> 
        </div>     
      </div>
    </div>     
  </div>          
  </section>

  <section class="section_footer">
    <div class="container">
      <div class="footer">
        <h1> 
          <a href="#">
            <i class="fa-solid fa-circle-up" style="color:#2a4359"> Back to top</i>
          </a>
        </h1>
      </div>
    </div>
  </section>

  {% endblock content %}

capp/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
      <!-- Font Awesome code -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

      <!--Import the Bootstrap CSS file:-->
      <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
      />
      <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
      />

      <!-- Mathjax -->
      <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
      <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

      
      <!-- CSS code -->
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='layout.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='carbon_app.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='methodology.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='about_us.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user.css') }}">

      <!-- To activate media queries in devices -->
      <meta name="viewport" content="user-scalable=yes, width=device-width, initial-scale=1">

         <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
      <!-- <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> -->

        {% if title %}
            <title>{{ title }}</title>
        {% else %}
            <title>home</title>
        {% endif %}
        
    </head>
    <body>
   <section class="section_navbar">
        <div class="container">
          <div class="navbar">
            <h1 class="logo">
              <a href="{{url_for('carbon_app.carbon_app_home')}}">CarbonCare <span class="text-logo"><i class="fa-solid fa-calculator"></i> </span> </a>
            </h1>
            {% if current_user.is_authenticated %}
            <nav>
               <ul>
                <li>
                 <a href="{{url_for('methodology.methodology_home')}}">Methodology <i class="fa-regular fa-newspaper"></i></a>
                </li>
                <li>
                  <a href="{{url_for('about_us.about_us_home')}}">About Us <i class="fa-solid fa-people-group"></i></a>
                </li>
                <li>
                  <a href="{{url_for('users.logout')}}">Logout <i class="fa-solid fa-arrow-right-from-bracket"></i></a>
                </li>
              </ul>
            </nav>
            {% else %}
            <nav>
              <ul>
               <li>
                <a href="{{url_for('methodology.methodology_home')}}">Methodology <i class="fa-regular fa-newspaper"></i></a>
               </li>
               <li>
                 <a href="{{url_for('about_us.about_us_home')}}">About Us <i class="fa-solid fa-people-group"></i></a>
               </li>
               <li>
                 <a href="{{url_for('users.login')}}">Login <i class="fa-solid fa-arrow-right-to-bracket"></i></a>
               </li>
               <li>
                 <a href="{{url_for('users.register')}}">Register <i class="fa-regular fa-address-card"></i></a>
               </li>
             </ul>
           </nav>
           {% endif %}
          </div>
        </div>
      </section>  
        {% block content %} {% endblock %}


        <!-- Bootstrap -->
        <!-- Question Accordion -->
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
          crossorigin="anonymous"
        ></script>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        
    </body>
</html>

capp/templates/methodology.html
{% extends "layout.html" %}
{% block content %}
  
<!-- Header -->
<section class="section_header_methodology">
    <div class="container">
  
      <div class="header">
        <div class="box"> 
          <h1 style="font-size:55px;"><span class="text-logo"> Methodology</span></h1>
          <p style="text-align:left;">
            Methodology is the philosophical evaluation of how knowledge and inquiry are framed within an academic discipline or school of thought (Oxford Reference, n.d). The methodology set the standard of what we want to achieve through our app: raising awareness about the carbon emissions that vehicles inflict on the environment. Therefore our app will provide a calculator that tracks the carbon emissions produced by different vehicles. If you need a more comprehensive methodology, please read our paper through the button below.
          </p>
          <div class="container_buttons_links_header">
            <div class="btn">
                <a href="https://acrobat.adobe.com/id/urn:aaid:sc:eu:d059225e-4be1-4283-b3d1-faafdc34e58f" target="_blank" class="btn btn-primary btn-lg mr-2", style="background-color:#35628f;">Paper</a>
            </div>
          </div>  
        </div>
        <div class="box">
          <img 
            src="{{url_for('static', filename='icons/methodology1.svg')}}"
            width="325" 
            height="325"
            alt=""/>
        </div>
      </div>
      
    </div>
</section> 

<!-- Methodology -->
<section class="section_body_methodology">
    <div class="container">

        <div class="methodology" style="display:block;">
            <h1 style="text-align:center;"> Our numbers and formulas:</h1>
        </div>

        <!--Enumerated list (table with two columns)-->
        <div class="methodology"> 
            <div class="box_table2" style="height:425px;">
                <ol start="1">
                    <li>
                        <h4> General Formula</h4>
                        <p class="text-left">
                            Air emissions from traffic vary depending on factors such as the vehicle type and fuel used. In the following, we will provide an overview of emission factors for various vehicles and traffic situations (Fedoryshyn, 2017). Our application will be based on one general formula. 
                            <br><br>
                        \( 𝐶𝑂2 = 𝑑 · 𝑒𝑓/𝑝 \)
                        </p>
                    </li>
                </ol>                        
            </div>
            <div class="box_table2" style="height:425px;">
                <ol start="2">
                    <li>
                        <h4>Formula for electrical vechicle </h4>
                        <p class="text-left">
                            The carbon intensity referred to in grams CO2/kwh in this formula (26 grams) is based on the carbon intensity in the western part of Norway (Electricity maps, 2023). We use data from the western part of Norway since this is where our target audience is based. For the energy consumption in kWh/km we use data from the average electric cars energy consumption, 0,194 kWh/km ( Ev-database, 2023)
                            <br></br>
                            \(CO2: 𝑑 ∗ 26 ∗ 𝑒𝑐/p \) 
                        </p>
                    </li>
                </ol>
            </div>  
        </div>

        <!--Enumerated list (table with two columns)-->
        <div class="methodology"> 
            <div class="box_table2" style="height:425px;">
                <ol start="3">
                    <li>
                        <h4>Car</h4>
                        <p class="text-left">
                        Old:
                        <Ul>
                            <li>Petrol car: 156,47g/km</li>
                            <li>Diesel car: 130,09g/km</li>
                        </Ul>
                        </p>
                        <p class="text-left">
                        New:
                        <Ul>
                            <li>Petrol car: 139g/km</li>
                            <li>Diesel car: 122,39g/km</li>
                        </Ul>
                        </p>
                    </li>
                    <li>
                        <h4>EL-car</h4>
                        <p class="text-left">
                            <Ul>
                                <li>Small car: 12g/km</li>
                                <li>Medium car: 16g/km</li>
                                <li>Large car: 20g/km</li>
                            </Ul>
                        </p>
                    </li>
                   
                    </li>
                </ol>                        
            </div>
            <div class="box_table2" style="height:425px;">
                <ol start="5">
                    <li>
                        <h4>Plane</h4>
                        <p class="text-left">
                            
                            Long-haul flights:
                        	<ul>
                            <li>Economy class: 102 g/km</li>
                            <li>Business class: 306 g/km</li>
                            <li>First class: 408 g/km</li>
                            </ul>
                        </p>
                        <p class="text-left">
                        Domestic and other short-haul flights:
                            <ul>
                            <li>Economy class: 133 g/km</li>
                            <li>Business class: 399 g/km</li>
                            <li>First class: 532 g/km</li>
                        </ul>
                        </p>
                    </li>
                
                </ol>
            </div>  
        </div>

        

        <!--Enumerated list (table with two column)-->
        <div class="methodology"> 
            <div class="box_table2" style="height:425px;">
                <ol start="6">
                    <li>
                        <h4>Ferry</h4>
                        <p class="text-left">
                            <ul>
                           <li> A fuel-driven ferry: 226 g/pkm </li>
                            </ul>
                        </p>
                    </li>
                    <br><br/>
                    <li>
                        <h4>Electric Ferry</h4>
                        <p class="text-left">
                         <ul>
                         <li>E-ferry: 5,25 grams CO2/pkm </li>
                        </ul>
                        </p>
                    </li>
                </ol>                        
            </div>
          <div class="box_table2" style="height:425px;">
                <ol start="8">
                    <li>
                        <h4>Train</h4>
                        <p class="text-left">
                            In 2021, traveling by train emitted 12.2 grams of CO2 per passenger kilometer, making it the most environmentally friendly option in Norway.
                        </p>
                        CO2 emissions per passenger kilometer generated when travelling by train in 2023:
                        <ul>
                           <li> Diesel Train European average: 91g CO2/pkm </li>
                           <li> Electric Train European average: 24g CO2/pkm</li>
                           <li> Electric Train in the Nordic Countries: 7g CO2/pkm </li>
                    </li>
            
                   
                </ol>
            </div>  
        </div>

        <!--Enumerated list (table with two column)-->
        <div class="methodology"> 
            <div class="box_table2" style="height:425px;">
                <ol start="9">
                    <li>
                        <h4>Bus</h4>
                        <p class="text-left">
                        The following numbers are estimated gas emissions in 2023:
                        <ul>
                            <li>European average diesel: 25 gram CO2/pkm</li>
                            <li>Average biodiesel: 7 gram C02/pkm</li>
                        </ul>  
                        </p>
                    </li>
                    <br><br/>
                    <li>
                        <h4>Electric Bus</h4>
                        <p class="text-left">
                            Electric: 13 gram C02/pkm
                        </p>
                    </li>
                    
                </ol>                        
            </div>
            <div class="box_table2" style="height:425px;">
                <ol start="11">
                
                    <li>
                        <h4>Motorcycle</h4>
                        <p class="text-left">
                            Petrol motorcycle UK average: 114g CO2/pkm
                        </p>
                    </li>
                   
                </ol>
            </div>  
        </div>
      
    </div>
</section>

<section class="section_footer">
    <div class="container">
      <div class="footer">
        <h1> 
          <a href="#">
            <i class="fa-solid fa-circle-up" style="color:#2a4359"> Back to top</i>
          </a>
        </h1>
      </div>
    </div>
  </section>

{% endblock content %}